### ISSUE TITLE
Endless loop in arbiter.Next freezes the game

### ISSUE THREAD

**Issue by marrasen** [jakecoffman/cp#37]
I'm developing a game where users can use their phones to control individual characters in the game. 

To test the performance I wrote a simulator that adds a 100 players, and the game completely froze. The game got stuck in an endless loop when calling `body.EachArbiter` from `SetVelocityUpdateFunc`.

This might be me using Chipmunk wrong, but I forked the chipmunk project and added escape counters to the four places where the Next function is called, and now the game runs fine without freezing.

My forks changes: https://github.com/jakecoffman/cp/compare/master...marrasen:cp:master

Is this a known issue? My game isn't public, but if needed I can try to reproduce this issue separately.

As a note, adding 100 players in the game is a mess and not at all playable, the characters get squeezed into small spaces which might be why this bug occurs.

**Comment by jakecoffman** [comment]
It would be easiest to diagnose the issue if you could share a reproduction of the problem.

I have [a game](https://github.com/jakecoffman/fam) which uses `body.EachArbiter` in `SetVelocityUpdateFunc` and my kids stress test it every so often and I haven't seen a freeze yet. So I don't think there's anything inherently wrong with the implementation, but bugs are always a possibility.

**Comment by marrasen** [comment]
I got this panic in bbtree once when I ran the game really hard for about an hour, so this one will probably be hard to write a reproduction of, but I will monitor it to see if it happens again. The receiver to `MarkLeafQuery` was nil.

My game has several levels where I between levels remove everything from the space and then add the new level back to the space. Maybe I should just create a new space for the new level and add my collision handlers back.

```
goroutine 46 [running]:
github.com/jakecoffman/cp/v2.(*Node).MarkLeafQuery(0x0, 0xc001d80460, 0x0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:174 +0x7a
github.com/jakecoffman/cp/v2.(*Node).MarkLeaf(0xc001d80460, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:158 +0x25e
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001d80460, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:354 +0x36
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00177d1d0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001770410, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00176c230, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0017709b0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001771a90, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0017796d0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001778910, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001778a50, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001d819f0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001d80550, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00104b7c0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001d81950, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001050780, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001050460, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00103e140, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00103fc20, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00104bae0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00104af00, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001050640, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001059ea0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001055b80, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001058b40, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001059360, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00105c500, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001060140, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001baddb0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc001738fa0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e2730, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e80f0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e8690, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e5090, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009ea230, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc00079eb90, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0003d7e50, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:356 +0x52
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e9db0, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0009e9c70, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*Node).MarkSubtree(0xc0007a0550, 0xc00072f4b0)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:357 +0x6c
github.com/jakecoffman/cp/v2.(*BBTree).ReindexQuery(0xc00061a580, 0x1910a40, {0x18b2440, 0xc00049e000})
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/bbtree.go:343 +0x230
github.com/jakecoffman/cp/v2.(*Space).Step(0xc00049e000, 0x3f91111111111111)
	C:/Users/marcu/go/pkg/mod/github.com/marrasen/cp/v2@v2.0.3/space.go:714 +0x2bd
main.(*Game).Update(0xc000128000)
	C:/Users/marcu/GolandProjects/balloons/cmd/game/main.go:301 +0x912
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Update(0xc0002780e0)
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/gameforui.go:112 +0x33
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0000d1080, {0x19734c8, 0xc0002d9970}, 0x1, 0x4094000000000000, 0x4086800000000000, 0x3ff0000000000000, 0xc0001e0308, 0x0)
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/internal/ui/context.go:154 +0x650
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc0000d1080, {0x19734c8, 0xc0002d9970}, 0x4094000000000000, 0x4086800000000000, 0x3ff0000000000000, 0xc0001e0308)
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/internal/ui/context.go:73 +0xbb
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).updateGame(0xc0001e0308)
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/internal/ui/ui_glfw.go:1491 +0x2f0
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).loopGame(0xc0001e0308)
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/internal/ui/ui_glfw.go:1448 +0xf1
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread.func2()
	C:/Users/marcu/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.8.0/internal/ui/run.go:71 +0x253
golang.org/x/sync/errgroup.(*Group).Go.func1()
	C:/Users/marcu/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0xa9
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	C:/Users/marcu/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0xe8

```

**Comment by jakecoffman** [comment]
That's great to hear! Maybe debug should be the default 🤔

**Comment by marrasen** [comment]
I think that would be a good idea, yes :)
I'm closing this issue, thanks for taking the time to answer me here.
